package me.redned.simreader.sc4.type;

public enum LotZoneType {
    UNKNOWN,
    RESIDENTIAL_LOW,
    RESIDENTIAL_MEDIUM,
    RESIDENTIAL_HIGH,
    COMMERCIAL_LOW,
    COMMERCIAL_MEDIUM,
    COMMERCIAL_HIGH,
    INDUSTRIAL_LOW,
    INDUSTRIAL_MEDIUM,
    INDUSTRIAL_HIGH,
    MILITARY,
    AIRPORT,
    SEAPORT,
    SPACEPORT,
    PLOPPED_BUILDING,
    PLOPPED_BUILDING_2 // ???
}
